on: [push, pull_request]
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.23.6
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"
          check-latest: true
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...
      - name: Run go vet
        continue-on-error: true
        run: go vet ./...
